import '../../../../../core/constants/api_endpoints.dart';
import '../../../../../core/constants/app_constants.dart';
import '../../../../../core/network/api_client.dart';
import '../../../../../core/network/paginated.dart';
import '../../../../../core/network/result.dart';
import '../../../../../core/utils/date_formatter.dart';
import '../../../../shared/data/models/application_model.dart';

class AdminApplicationRepository {
  const AdminApplicationRepository(this._client);

  final ApiClient _client;

  Future<Result<Paginated<ApplicationModel>>> list({
    int page = 1,
    ApplicationStatus? status,
    String? search,
  }) =>
      _client.get(
        ApiEndpoints.adminApplications,
        query: {
          'page': page,
          'limit': AppConstants.pageSize,
          if (status != null) 'status': status.value,
          if (search != null && search.isNotEmpty) 'search': search,
        },
        decoder: (data) => Paginated.fromJson(data, ApplicationModel.fromJson),
      );

  Future<Result<ApplicationModel>> detail(int id) => _client.get(
        ApiEndpoints.adminApplication(id),
        decoder: (data) => ApplicationModel.fromJson(data as Map<String, dynamic>),
      );

  /// Issues the policy. Omitted values are generated by the backend.
  Future<Result<ApplicationModel>> approve({
    required int id,
    String? policyNumber,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      _client.patch(
        ApiEndpoints.adminApplicationDecide(id),
        body: {
          'action': 'APPROVE',
          if (policyNumber != null && policyNumber.isNotEmpty) 'policy_number': policyNumber,
          if (startDate != null) 'start_date': DateFormatter.api(startDate),
          if (endDate != null) 'end_date': DateFormatter.api(endDate),
        },
        decoder: (data) => ApplicationModel.fromJson(data as Map<String, dynamic>),
      );

  Future<Result<ApplicationModel>> reject({required int id, required String reason}) => _client.patch(
        ApiEndpoints.adminApplicationDecide(id),
        body: {'action': 'REJECT', 'reason': reason},
        decoder: (data) => ApplicationModel.fromJson(data as Map<String, dynamic>),
      );
}
